### ISSUE TITLE
Make it possible to use connected Input without Formsy.Form

### ISSUE THREAD

**Issue by hbarylskyi** [track0x1/formsy-react-native#2]
Hi! Thanks for the lib. As for now, it's not possible to use Input exported with `export default Formsy.withFormsy(Input)` without wrapping it with Formsy.Form:

```
<Formsy.Form ref="form" onValidSubmit={this.handleSubmit}>
  <Input 
  ...  
  />
</Formsy.Form>
```

vs 

```
<Input
...
/>
```

Can this feature be added?

**Comment by track0x1** [comment]
Hi,
All inputs / form fields will need to be wrapped to be incorporated into Formsy.
Have you seen this example? https://github.com/track0x1/formsy-react-native/blob/master/examples/components/TextField.js
